# default config
baseURL = "https://abchalet.com"
languageCode = "en-us"
title = "ABChalet"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 6

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

# default parameter
[params]
logo = "https://abchalet.com/static/uploads/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "chalet, cabin, laurentians, canadian, kayak, airbnb"
# Preloader
preloader = true
# search
search = true
# about author
author = "heri"
author_image = "images/banner-img.png"
bio = "Built on the banks of Rivi√®re Rouge, where mountains and majestic pine forests meet, the log cabin welcomes you year round in the tranquility and beauty of the great Canadian Outdoors."
# Contact info
mobile = "+514 800 1000"
email = "bonheur@abchalet.com"
address = "435 Ch des Dunes Riviere Rouge"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 ABChalet.com"

# Instagram feed
[params.instafeed]
enable = true
user_id = "24615923"
access_token = "24615923.b961e43.73ec724c7f9447988e3ee44f241c1058"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/heri.rakotomalala/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/heri"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/heri"